# Generated by Django 4.2.7 on 2023-11-13 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_teacher_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 11, 4, 29, 347712, tzinfo=datetime.timezone.utc)),
        ),
    ]
