# Generated by Django 4.2.7 on 2023-11-13 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_certificate_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 11, 59, 47, 425242, tzinfo=datetime.timezone.utc)),
        ),
    ]
